image: Visual Studio 2019


stack: node 12  


branches:  
  only:    
    - master


gitcache: node_modules  


install:  
  - npm install  


build: off


test_script:  
    - npm run lint && npm test  

